### ISSUE TITLE
Speakers view

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#15]
We need a view displayed as block on the home page, featuring 6 speakers.
Mary Chris already started it on her local.

**Comment by Luukyb** [comment]
Of course, the view needs to match up with the markup of the prototype in folder pre-drupalsite

**Comment by Luukyb** [comment]
Great work MC. We will also need a display on the speakers view as page.
This is where the link in the main menu "Speakers" will go.

**Comment by johnrosswvsu** [comment]
Will continue work from here.

**Comment by johnrosswvsu** [comment]
Updated views for speakers and renamed a few features for uniformity.

config_environment_indicator_feature -> config_environment_indicator
views_speakers_views_feature -> views_speakers
media_image_styles_feature -> media_image_styles
Please also note that the speaker name has no style, same with the original views. I am afraid to touch the css, because it looks like the sass files are not updated.

https://github.com/Luukyb/DrupalcampCebu2014/pull/26

http://screencast.com/t/AtKAaBnp

**Comment by Luukyb** [comment]
Merged https://github.com/Luukyb/DrupalcampCebu2014/pull/26
