### ISSUE TITLE
Content type page

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#18]
Generic page content type need to be used.
See wiki for details about the fields.
Ex: for the page "How to become a sponsor"

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,
- Instead of using a feature, I have simulated how the standard profile installation creates the basic page and articles node types which are done through hook install of the intsallation profile.
- Also updated Cebu to user upper case in the intro message, checked with Miss Jinky.

https://github.com/Luukyb/DrupalcampCebu2014/pull/23
