### ISSUE TITLE
fix missing images

### ISSUE THREAD

**Issue by mtem27** [Luukyb/DrupalcampCebu2014#78]
images are missing

**Comment by mtem27** [comment]
updated directory permissions & re-uploaded images

**Comment by Luukyb** [comment]
What were the images ?

**Comment by johnrosswvsu** [comment]
After properly looking into it: It think I unintentionally delete the images when creating a new release branch. After experiencing permission denied when checking out a new release branch, git status showed a lot of untracked files so I have to remove them.

This is on the bash history of promet user.

---

git merge release-0.2 -> This is where I experienced a permission denied since ownership to directories was root, instead of promet
git statu
git status
git reset  --hard origin/develop 
git status
sudo rm -r docroot/sites/all
rm -r pre-drupalsite/public/images/book-now-bg.png
rm -r docroot/sites
clear
git status
git checkout .
git status
sudo git branch
sudo git merge release-0.2

---

The creation of a new release branch could be determined through on "git reflog --date=local"

677d476 HEAD@{Mon Sep 29 06:23:48 2014}: merge develop: Fast-forward
4d88083 HEAD@{Mon Sep 29 06:23:41 2014}: checkout: moving from develop to release-0.2
677d476 HEAD@{Mon Sep 29 06:23:30 2014}: pull : Fast-forward
4d88083 HEAD@{Mon Sep 29 06:23:24 2014}: checkout: moving from release-0.2 to develop
4d88083 HEAD@{Sun Sep 28 20:33:59 2014}: checkout: moving from develop to release-0.2
4d88083 HEAD@{Sun Sep 28 20:33:26 2014}: merge release-0.2: Fast-forward
6e6eafb HEAD@{Sun Sep 28 20:30:45 2014}: checkout: moving from release-0.2 to develop

Thanks.
